# Copyright (c) 2016 Kazumasa Kohtaka. All rights reserved.
# This file is available under the MIT license.

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
  - name: web
    port: 9200
    targetPort: 9200
    nodePort: 31080
  - name: api
    port: 9300
    targetPort: 9300
