# Copyright (c) 2016 Kazumasa Kohtaka. All rights reserved.
# This file is available under the MIT license.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch
        args:
        - -Des.cluster.name=graylog
        - -Des.discovery.zen.ping.multicast.enabled=false
        - -Des.discovery.zen.ping.unicast.hosts=127.0.0.1:9300
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
