# Copyright (c) 2016 Kazumasa Kohtaka. All rights reserved.
# This file is available under the MIT license.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graylog
spec:
  replicas: 1
  template:
    metadata:
      name: graylog
      labels:
        app: graylog
    spec:
      containers:
      - name: graylog
        image: graylog2/server
        ports:
        - containerPort: 9000
        - containerPort: 12900
        - containerPort: 12201
        env:
        - name: GRAYLOG_WEB_LISTEN_URI
          value: http://0.0.0.0:9000/
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://mongodb:27017/graylog
        - name: GRAYLOG_ELASTICSEARCH_DISCOVERY_ZEN_PING_MULTICAST_ENABLED
          value: "false"
        - name: GRAYLOG_ELASTICSEARCH_DISCOVERY_ZEN_PING_UNICAST_HOSTS
          value: "elasticsearch:9300"
        - name: GRAYLOG_WEB_ENDPOINT_URI
          value: "http://graylog.dev:30180"
        resources:
          requests:
            cpu: "100m"
            memory: "1000Mi"
