# Copyright (c) 2016 Kazumasa Kohtaka. All rights reserved.
# This file is available under the MIT license.

apiVersion: v1
kind: Service
metadata:
  name: graylog
spec:
  selector:
    app: graylog
  type: NodePort
  ports:
  - name: web
    port: 9000
    targetPort: 9000
    nodePort: 30080
  - name: api
    port: 12900
    targetPort: 12900
    nodePort: 30180
  - name: gelf
    port: 12201
    targetPort: 12201
